### ISSUE TITLE
the module isn't working at all, I don't get any notifications for YouTube videos.

### ISSUE THREAD

**Issue by MarvNC** [Ashish-Bansal/OneTapYoutubeModule#1]
---

Feb 19, 2016 3:58:28 PM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KTU84P' with fingerprint 'Xiaomi/dior/dior:4.4.4/KTU84P/V7.1.1.0.KHIMICK:user/release-keys'
Loading modules from /data/app/com.phantom.onetapvideodownload-1.apk
  Loading class com.phantom.onetapvideodownload.MediaPlayerHook
Loading modules from /data/app/com.phantom.onetapyoutubemodule-1.apk
  Loading class com.phantom.onetapyoutubemodule.YoutubeMediaHook
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
    at dalvik.system.DexFile.defineClassNative(Native Method)
    at dalvik.system.DexFile.defineClass(DexFile.java:222)
    at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
    at dalvik.system.DexPathList.findClass(DexPathList.java:322)
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
    at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:421)
    at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by Ashish-Bansal** [comment]
Thanks for reporting this. You must be using Dalvik instead of ART.
I'll fix it soon.

**Comment by MarvNC** [comment]
I use redmi note 4g by the way, of that helps.

**Comment by Ashish-Bansal** [comment]
@smartymarv It has already been fixed ;)

Next release will have this fix.

**Comment by MarvNC** [comment]
Oh OK thanks. What's dalvik and art?

**Comment by Ashish-Bansal** [comment]
@smartymarv You can read about dalvik and art from here : 
http://opensourceforgeeks.blogspot.in/2015/02/difference-between-dalvik-and-art.html
